# GeoSight in-da-house Justfile
# For Raspberry Pi OS trixie 64bit on Raspberry Pi 4B
# Based on knowledge from UNopenGIS/7 issue #821

# Default variables - optimized for Raspberry Pi 4B (4GB RAM)
GEOSIGHT_REPO := "https://github.com/unicef-drp/GeoSight-OS.git"
GEOSIGHT_DIR := "GeoSight-OS"
HTTP_PORT := "2000"
HTTPS_PORT := "2443"

# Raspberry Pi optimized settings
# These can be overridden with: just --set VARIABLE value
COMPOSE_HTTP_TIMEOUT := "300"
DOCKER_CLIENT_TIMEOUT := "300"

# Docker resource limits for Raspberry Pi (optional, uncomment if needed)
# DOCKER_MEMORY_LIMIT := "2g"
# DOCKER_CPU_LIMIT := "2"

# Default recipe: show available commands
default:
    @just --list

# Check prerequisites
_check-docker:
    #!/usr/bin/env bash
    set -euo pipefail
    if ! command -v docker &> /dev/null; then
        echo "❌ Docker is not installed. Run 'just install' first."
        exit 1
    fi
    if ! docker info &> /dev/null; then
        echo "❌ Docker daemon is not running or you don't have permission."
        echo "   Try: sudo systemctl start docker"
        echo "   Or: log out and log back in if you just added yourself to the docker group"
        exit 1
    fi

# Check if GeoSight directory exists
_check-geosight:
    #!/usr/bin/env bash
    set -euo pipefail
    if [ ! -d "{{GEOSIGHT_DIR}}" ]; then
        echo "❌ GeoSight-OS directory not found. Run 'just install' first."
        exit 1
    fi

# Generate a random secret key
_generate-secret-key:
    #!/usr/bin/env bash
    openssl rand -base64 32 | tr -d '/+=' | head -c 50

# Install all required packages and clone GeoSight-OS
install:
    #!/usr/bin/env bash
    set -euo pipefail
    
    echo "======================================"
    echo "  Installing GeoSight for Raspberry Pi"
    echo "======================================"
    echo ""
    
    # Update package lists
    echo "📦 Updating package lists..."
    sudo apt-get update
    
    # Install required packages
    echo "📦 Installing required packages..."
    sudo apt-get install -y \
        git \
        docker.io \
        docker-compose \
        curl \
        make \
        openssl
    
    # Enable and start Docker
    echo "🐳 Enabling Docker service..."
    sudo systemctl enable docker
    sudo systemctl start docker
    
    # Add current user to docker group if not already
    if ! groups | grep -q docker; then
        echo "👤 Adding user to docker group..."
        sudo usermod -aG docker $USER
        echo ""
        echo "⚠️  IMPORTANT: Docker group membership added."
        echo "   Please log out and log back in, then run:"
        echo "   just install"
        echo ""
        exit 0
    fi
    
    # Verify docker works
    if ! docker info &> /dev/null; then
        echo "⚠️  Docker is running but you may need to log out and log back in"
        echo "   for group permissions to take effect."
        exit 1
    fi
    
    # Clone GeoSight-OS if not exists
    if [ ! -d "{{GEOSIGHT_DIR}}" ]; then
        echo "📥 Cloning GeoSight-OS repository..."
        git clone --depth 1 {{GEOSIGHT_REPO}}
    else
        echo "✅ GeoSight-OS directory already exists"
        echo "   Pulling latest changes..."
        cd {{GEOSIGHT_DIR}} && git pull || true
        cd ..
    fi
    
    # Run setup
    echo "🔧 Running GeoSight setup..."
    cd {{GEOSIGHT_DIR}}
    
    # Generate random secret key
    SECRET_KEY=$(openssl rand -base64 32 | tr -d '/+=' | head -c 50)
    
    # Create .env file with Raspberry Pi optimized settings
    if [ ! -f deployment/.env ]; then
        echo "🔧 Creating deployment/.env with Raspberry Pi optimized settings..."
        cat > deployment/.env << ENVEOF
# GeoSight configuration optimized for Raspberry Pi 4B
# Generated by geosight-in-da-house on $(date)

# Security - This key was randomly generated
SECRET_KEY=${SECRET_KEY}

COMPOSE_PROJECT_NAME=geosight
NGINX_TAG=0.0.1
DJANGO_TAG=3.1.0

# Django settings
DJANGO_SETTINGS_MODULE=core.settings.prod
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin
ADMIN_EMAIL=admin@example.com
INITIAL_FIXTURES=True

# Port configuration - default 2000 for Raspberry Pi
HTTP_PORT={{HTTP_PORT}}
HTTPS_PORT={{HTTPS_PORT}}

# Sentry - disabled by default for Raspberry Pi
SENTRY_DSN=
SENTRY_ENVIRONMENT=development

# Redis configuration
REDIS_HOST=redis
REDIS_PASSWORD=redis_password

# Database configuration
DATABASE_NAME=django
DATABASE_USERNAME=docker
DATABASE_PASSWORD=docker
DATABASE_HOST=db
RABBITMQ_HOST=rabbitmq

# Azure B2C - disabled by default
AZURE_B2C_CLIENT_ID=
AZURE_B2C_CLIENT_SECRET=
AZURE_B2C_TENANT_NAME=
AZURE_B2C_POLICY_NAME=

# Email - disabled by default
EMAIL_HOST=
EMAIL_PORT=
EMAIL_HOST_USER=
EMAIL_HOST_PASSWORD=
EMAIL_USE_TLS=
EMAIL_USE_SSL=
DEFAULT_FROM_EMAIL=

# Log rotation - reduced for Raspberry Pi storage constraints
LOGROTATE_COPIES=7
LOGROTATE_SIZE=50M
LOGROTATE_INTERVAL=daily

# App domain
APP_DOMAIN=localhost

# Plugins - minimal set for Raspberry Pi resource constraints
PLUGINS=cloud_native_gis,reference_dataset
ENVEOF
        echo "✅ deployment/.env file created with secure random SECRET_KEY"
    else
        echo "✅ deployment/.env already exists"
    fi
    
    # Create docker-compose override if not exists
    if [ ! -f deployment/docker-compose.override.yml ]; then
        echo "🔧 Creating docker-compose.override.yml..."
        cp deployment/docker-compose.override.template.yml deployment/docker-compose.override.yml
        echo "✅ docker-compose.override.yml created"
    else
        echo "✅ docker-compose.override.yml already exists"
    fi
    
    # Pull required images for ARM64
    echo "🐳 Pulling Docker images for ARM64..."
    ARCH=$(uname -m)
    PLATFORM="linux/amd64"
    [[ "$ARCH" == "arm64" || "$ARCH" == "aarch64" ]] && PLATFORM="linux/arm64"
    docker pull --platform=$PLATFORM ubuntu:22.04
    
    echo ""
    echo "======================================"
    echo "  ✅ Installation complete!"
    echo "======================================"
    echo ""
    echo "Next steps:"
    echo "  1. Run 'just run' to start GeoSight"
    echo "  2. Access http://localhost:{{HTTP_PORT}}/"
    echo "  3. Login with admin / admin"
    echo ""

# Run GeoSight in development mode
run: _check-docker _check-geosight
    #!/usr/bin/env bash
    set -euo pipefail
    
    echo "======================================"
    echo "  Starting GeoSight"
    echo "======================================"
    echo ""
    
    cd {{GEOSIGHT_DIR}}
    
    # Set Docker timeouts for Raspberry Pi (slower I/O)
    export COMPOSE_HTTP_TIMEOUT={{COMPOSE_HTTP_TIMEOUT}}
    export DOCKER_CLIENT_TIMEOUT={{DOCKER_CLIENT_TIMEOUT}}
    
    # Create redis directory with correct permissions (required for redis container)
    if [ ! -d deployment/volumes/tmp_data/redis ]; then
        echo "📁 Creating Redis directory with correct permissions..."
        sudo mkdir -p deployment/volumes/tmp_data/redis
        sudo chown -R 999:999 deployment/volumes/tmp_data/redis
    else
        sudo chown -R 999:999 deployment/volumes/tmp_data/redis
    fi
    
    # Run development mode
    echo "🚀 Starting Docker containers..."
    echo "   (This may take 10-30 minutes on first run on Raspberry Pi)"
    echo ""
    make dev
    
    echo ""
    echo "⏳ Waiting for services to initialize (60 seconds)..."
    sleep 60
    
    # Initialize the application
    echo "🔧 Initializing GeoSight database and settings..."
    make dev-initialize
    
    # Load demo data
    echo "📊 Loading demo data..."
    make load-test-data
    
    echo ""
    echo "======================================"
    echo "  ✅ GeoSight is running!"
    echo "======================================"
    echo ""
    echo "🌐 Access GeoSight at: http://localhost:{{HTTP_PORT}}/"
    echo "🔑 Login credentials: admin / admin"
    echo ""
    echo "Useful commands:"
    echo "  just stop     - Stop GeoSight"
    echo "  just status   - Show container status"
    echo "  just logs     - View logs"
    echo "  just tunnel   - Expose to internet via Cloudflare"
    echo ""

# Stop GeoSight
stop: _check-geosight
    #!/usr/bin/env bash
    set -euo pipefail
    
    echo "🛑 Stopping GeoSight..."
    cd {{GEOSIGHT_DIR}}
    make down
    echo "✅ GeoSight stopped"

# Restart GeoSight
restart: stop
    #!/usr/bin/env bash
    set -euo pipefail
    
    echo "🔄 Restarting GeoSight..."
    cd {{GEOSIGHT_DIR}}
    
    export COMPOSE_HTTP_TIMEOUT={{COMPOSE_HTTP_TIMEOUT}}
    export DOCKER_CLIENT_TIMEOUT={{DOCKER_CLIENT_TIMEOUT}}
    
    # Ensure redis directory has correct permissions
    sudo chown -R 999:999 deployment/volumes/tmp_data/redis 2>/dev/null || true
    
    make dev
    
    echo ""
    echo "⏳ Waiting for services to start..."
    sleep 30
    echo "✅ GeoSight restarted"
    echo ""
    echo "🌐 Access at: http://localhost:{{HTTP_PORT}}/"

# Uninstall GeoSight (remove containers, images, and optionally the repository)
uninstall:
    #!/usr/bin/env bash
    set -euo pipefail
    
    echo "======================================"
    echo "  Uninstalling GeoSight"
    echo "======================================"
    echo ""
    
    if [ -d "{{GEOSIGHT_DIR}}" ]; then
        cd {{GEOSIGHT_DIR}}
        
        # Stop and remove containers
        echo "🛑 Stopping and removing containers..."
        make down 2>/dev/null || true
        
        cd ..
        
        # Remove Docker volumes
        echo "🗑️  Removing Docker volumes..."
        docker volume rm \
            geosight_static-data \
            geosight_media-data \
            geosight_database \
            geosight_backups-data \
            geosight_rabbitmq \
            geosight_redis-data \
            geosight_tmp-data \
            geosight_tmp-logrotate \
            2>/dev/null || true
        
        # Ask about removing the repository
        echo ""
        read -p "Remove GeoSight-OS directory? This will delete all local data. [y/N] " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            echo "🗑️  Removing GeoSight-OS directory..."
            sudo rm -rf {{GEOSIGHT_DIR}}
            echo "✅ Directory removed"
        else
            echo "📁 Directory kept at: {{GEOSIGHT_DIR}}"
        fi
    else
        echo "⚠️  GeoSight-OS directory not found - nothing to uninstall"
    fi
    
    echo ""
    echo "✅ Uninstall complete"

# Create Cloudflare Tunnel for internet access
tunnel: _check-geosight
    #!/usr/bin/env bash
    set -euo pipefail
    
    echo "======================================"
    echo "  Creating Cloudflare Tunnel"
    echo "======================================"
    echo ""
    
    # Check if cloudflared is installed
    if ! command -v cloudflared &> /dev/null; then
        echo "📦 Installing cloudflared..."
        
        # Detect architecture
        ARCH=$(uname -m)
        if [[ "$ARCH" == "aarch64" || "$ARCH" == "arm64" ]]; then
            CLOUDFLARED_ARCH="arm64"
        else
            CLOUDFLARED_ARCH="amd64"
        fi
        
        # Download and install cloudflared
        CLOUDFLARED_URL="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${CLOUDFLARED_ARCH}.deb"
        echo "   Downloading from: ${CLOUDFLARED_URL}"
        curl -L -o /tmp/cloudflared.deb "${CLOUDFLARED_URL}"
        sudo dpkg -i /tmp/cloudflared.deb
        rm /tmp/cloudflared.deb
        
        echo "✅ cloudflared installed"
    else
        echo "✅ cloudflared is already installed"
    fi
    
    echo ""
    echo "🌐 Starting Cloudflare Tunnel..."
    echo ""
    echo "   This will create a temporary public URL for your GeoSight instance."
    echo "   The URL will be displayed below after the tunnel is established."
    echo ""
    echo "   ⚠️  Security note: Anyone with this URL can access your GeoSight."
    echo "   Press Ctrl+C to stop the tunnel."
    echo ""
    
    cloudflared tunnel --url http://localhost:{{HTTP_PORT}}

# Run install and then run (full setup)
doit: install run

# Show container status
status: _check-docker
    #!/usr/bin/env bash
    set -euo pipefail
    
    echo "📊 GeoSight Container Status:"
    echo ""
    if [ -d "{{GEOSIGHT_DIR}}" ]; then
        cd {{GEOSIGHT_DIR}}
        docker compose -f deployment/docker-compose.yml -f deployment/docker-compose.override.yml ps
    else
        echo "⚠️  GeoSight-OS directory not found. Run 'just install' first."
    fi

# View logs
logs: _check-geosight
    #!/usr/bin/env bash
    set -euo pipefail
    
    cd {{GEOSIGHT_DIR}}
    docker compose -f deployment/docker-compose.yml -f deployment/docker-compose.override.yml logs -f

# Access Django shell
shell: _check-geosight
    #!/usr/bin/env bash
    set -euo pipefail
    
    cd {{GEOSIGHT_DIR}}
    make dev-shell

# Clean up Docker resources (use with caution)
clean:
    #!/usr/bin/env bash
    set -euo pipefail
    
    echo "🧹 Cleaning up Docker resources..."
    echo ""
    
    read -p "This will remove unused Docker resources. Continue? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        docker system prune -f
        echo "✅ Cleanup complete"
    else
        echo "Cleanup cancelled"
    fi

# Show system information relevant for GeoSight
info:
    #!/usr/bin/env bash
    set -euo pipefail
    
    echo "======================================"
    echo "  System Information"
    echo "======================================"
    echo ""
    echo "Architecture: $(uname -m)"
    echo "OS: $(cat /etc/os-release | grep PRETTY_NAME | cut -d'"' -f2)"
    echo "Kernel: $(uname -r)"
    echo ""
    echo "Memory:"
    free -h | head -2
    echo ""
    echo "Disk:"
    df -h / | tail -1
    echo ""
    if command -v docker &> /dev/null; then
        echo "Docker: $(docker --version)"
    else
        echo "Docker: Not installed"
    fi
    if [ -d "{{GEOSIGHT_DIR}}" ]; then
        echo "GeoSight-OS: Installed at ./{{GEOSIGHT_DIR}}"
    else
        echo "GeoSight-OS: Not installed"
    fi
